// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_media: dynamic(() => import("./ArticleMedia")),
  blog_launcher: dynamic(() => import("./BlogLauncher")),
  body: dynamic(() => import("./ArticleBody")),
  contact_block: dynamic(() => import("./ContactBlock")),
  home_launcher: dynamic(() => import("./HomeLauncher")),
};
