import type { Metadata } from "next";
import localFont from "next/font/local";
import clsx from "clsx";
import { createClient } from "@/prismicio";

import "./globals.css";
import { Header } from "./components/Header/Header";
import { Lenis } from "./components/Lenis";

const neueHaasUnica = localFont({
  src: [
    {
      path: "./fonts/NeueHaasUnicaW06Black.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-neueHaasUnica",
});

const coupeur = localFont({
  src: [
    {
      path: "./fonts/CoupeurMonospace-Bold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-coupeur",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();

  const { data } = await client.getSingle("settings");

  return (
    <html lang="en">
      <Lenis>
        <body
          className={clsx(neueHaasUnica.variable, coupeur.variable)}
          data-lenis-prevent="true"
        >
          <Header
            menu={data.menu}
            instagram={data.instagram as string}
            linkedin={data.linkedin as string}
            mail={data.mail as string}
            phone={data.phone as string}
          />
          {children}
        </body>
      </Lenis>
    </html>
  );
}
